# Generated by Django 4.2.21 on 2025-05-27 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True, verbose_name='Código')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
                ('nome', models.CharField(max_length=45, null=True, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=45, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=45, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='Cep')),
                ('telefone', models.CharField(blank=True, max_length=45, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=45, verbose_name='Email')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'atendimento',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('periodicidade', models.CharField(choices=[('M', 'Mensal'), ('B', 'Bimestral'), ('T', 'Trimestral'), ('S', 'Semestral'), ('A', 'Anual')], max_length=45, verbose_name='Periodicidade da Atividade')),
                ('problema', models.TextField(blank=True, verbose_name='Relatar problema')),
                ('inicio_manutencao', models.DateField(blank=True, null=True, verbose_name='Data Início da Manutenção')),
                ('ultima_manutencao', models.DateField(blank=True, null=True, verbose_name='Última Manutenção')),
                ('termino_manutencao', models.DateField(blank=True, null=True, verbose_name='Data de Término da Manutenção')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Atrasado', 'Atrasado'), ('Concluído', 'Concluído')], default='Pendente', max_length=45, verbose_name='Status')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('pf', 'Pessoal Física'), ('pj', 'Pessoa Jurídica')], max_length=4)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('nome', models.CharField(max_length=45, null=True, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=45, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=45, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=45, verbose_name='Cep')),
                ('telefone', models.CharField(blank=True, max_length=45, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=45, verbose_name='Email')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregao', models.CharField(max_length=45, null=True, verbose_name='Pregão')),
                ('contrato', models.CharField(max_length=45, null=True, verbose_name='Contrato')),
                ('objeto', models.TextField(blank=True, verbose_name='Objeto do Contrato')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Contratual (Global)')),
                ('expectativa_faturamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expectativa de faturamento mensal (Conforme Aditivos)')),
                ('qtd_equipamento_ativo', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Equipamentos Ativos')),
                ('qtd_equipamento_inativo', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Equipamentos Inativos')),
                ('equipe_fixa', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=45, null=True, verbose_name='Equipe fixa')),
                ('qtd_equipe', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Quantidade de equipe')),
                ('veiculo', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Quantidade de veículos')),
                ('pagt_pecas', models.CharField(blank=True, max_length=45, null=True, verbose_name='Quem paga as peças')),
                ('pagt_corretivas', models.CharField(blank=True, max_length=45, null=True, verbose_name='Quem paga as corretivas')),
                ('pagt_mensal_demanda', models.CharField(blank=True, choices=[('Mensal', 'Mensal'), ('Demanda', 'Demanda')], max_length=45, null=True, verbose_name='Pagamento é mensal ou por demanda')),
                ('periodicidade', models.CharField(blank=True, max_length=45, null=True, verbose_name='Periodicidade das preventivas - (MENSAL/BIMESTRAL/SEMESTRAL/ANUAL)')),
                ('inicio_contrato', models.DateField(blank=True, null=True, verbose_name='Inicio do contrato')),
                ('periodo_renovacao', models.CharField(blank=True, max_length=45, null=True, verbose_name='Periodo de renovação - EX.: 01 (UM) ANO OU 02 (DOIS) ANOS e 12 (DOZE) DIAS)')),
                ('fim_contrato', models.DateField(blank=True, null=True, verbose_name='Fim do contrato')),
                ('data_renovacao', models.DateField(blank=True, null=True, verbose_name='Data de renovação')),
                ('vigencia_final', models.CharField(blank=True, max_length=45, null=True, verbose_name='Vigência final')),
                ('prazo_corretiva', models.TextField(blank=True, verbose_name='Prazo de corretivas')),
                ('link_doc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link dos documentos')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('pf', 'Pessoal Física'), ('pj', 'Pessoa Jurídica')], max_length=4)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=45, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=45, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=45, verbose_name='Cep')),
                ('telefone', models.CharField(blank=True, max_length=45, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=45, verbose_name='Email')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True, verbose_name='Código')),
                ('tipo', models.CharField(max_length=45, null=True, verbose_name='Tipo')),
                ('ambiente', models.CharField(blank=True, max_length=45, null=True, verbose_name='Ambiente')),
                ('marca', models.CharField(blank=True, max_length=45, null=True, verbose_name='Marca')),
                ('tag', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tag')),
                ('numero_serie', models.CharField(blank=True, max_length=45, null=True, verbose_name='Número de Série')),
                ('capacidade', models.CharField(blank=True, max_length=45, null=True, verbose_name='Capacidade')),
                ('mod_evaporador', models.CharField(blank=True, max_length=45, null=True, verbose_name='Modelo de Evaporador')),
                ('mod_condensador', models.CharField(blank=True, max_length=45, null=True, verbose_name='Modelo de Condensador')),
                ('gas_refrigerante', models.CharField(blank=True, max_length=45, null=True, verbose_name='Gás Refrigerante')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
        migrations.CreateModel(
            name='Responsavel_Tecnico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('pf', 'Pessoal Física'), ('pj', 'Pessoa Jurídica')], max_length=4)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('nome', models.CharField(max_length=45, null=True, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=45, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=45, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=45, verbose_name='Cep')),
                ('telefone', models.CharField(blank=True, max_length=45, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=45, verbose_name='Email')),
                ('rigistro_conselho', models.CharField(blank=True, max_length=45, null=True, verbose_name='Registro no Conselho de Classe')),
                ('art', models.CharField(blank=True, max_length=45, null=True, verbose_name='ART')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resp_tecnico',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
    ]
