# Generated by Django 5.0.1 on 2024-03-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='usuario_empresa',
            new_name='usuario',
        ),
    ]
