# Generated by Django 5.0.1 on 2024-03-17 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='resp_tecnico',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to='cadastros.responsavel_tecnico'),
        ),
    ]
