# Generated by Django 5.0.1 on 2024-03-17 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_empresa_resp_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel_tecnico',
            name='resp_tecnico',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Responsavel_Tecnico', to='cadastros.empresa'),
        ),
    ]
