# Generated by Django 5.0.1 on 2024-03-17 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_responsavel_tecnico_resp_tecnico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel_tecnico',
            name='resp_tecnico',
        ),
        migrations.AddField(
            model_name='responsavel_tecnico',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Responsavel_Tecnico', to='cadastros.empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='resp_tecnico',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_do_responsavel', to='cadastros.responsavel_tecnico'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_do_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
