# Generated by Django 5.0.1 on 2024-03-19 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_remove_responsavel_tecnico_resp_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa'),
        ),
    ]
