# Generated by Django 5.0.1 on 2024-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_atendimento_empresa_atividade_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='Cep'),
        ),
    ]
