# Generated by Django 5.0.1 on 2024-03-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_atendimento_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='resp_tecnico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_do_responsavel', to='cadastros.responsavel_tecnico'),
        ),
    ]
