# Generated by Django 5.0.1 on 2024-03-16 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.CharField(max_length=45, null=True, verbose_name='Competencia')),
                ('preventiva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preventiva')),
                ('corretiva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Corretiva')),
                ('instalacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Instalação')),
                ('pecas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peças')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.contrato')),
            ],
            options={
                'db_table': 'financeiro',
            },
        ),
    ]
